In [1]:
import torch
import torch.nn as nn

In [3]:
prediction=torch.randn(4,5)
print(prediction)

tensor([[ 0.7905, -0.2445,  0.2189, -0.6416,  3.0126],
        [-2.1067, -0.5788, -2.5010,  0.9603,  0.1629],
        [ 1.2672, -0.7073,  0.4163,  0.3323,  0.5623],
        [-0.4495,  1.3970, -0.0739,  1.2121, -1.0448]])


In [5]:
label=torch.randn(4,5)

In [21]:
mse = nn.MSELoss(reduction='none')

In [22]:
loss = mse(prediction,label)
loss

tensor([[2.6847e+00, 3.7790e-01, 1.2519e-01, 9.5778e-03, 3.7143e+00],
        [1.1841e+01, 1.8163e-01, 1.0595e+01, 3.1595e+00, 1.8694e+00],
        [1.1360e+01, 1.6242e+00, 3.9965e+00, 4.7371e-02, 4.5330e-04],
        [3.2033e-01, 3.5005e-02, 1.6538e-01, 4.4521e-08, 2.7713e+00]])

In [23]:
mse = nn.MSELoss(reduction='mean')
loss = mse(prediction,label)
loss

tensor(2.7440)

In [24]:
mse = nn.MSELoss(reduction='sum')
loss = mse(prediction,label)
loss

tensor(54.8790)

In [25]:
((prediction-label)**2).mean()

tensor(2.7440)

In [30]:
label=torch.zeros(4,5).random_(0,2)
label

tensor([[0., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [0., 1., 0., 0., 1.],
        [0., 0., 0., 1., 0.]])

In [34]:
sigmoid = nn.Sigmoid()

In [37]:
bce = nn.BCELoss(reduction='mean')
bce(sigmoid(prediction),label)

tensor(0.8186)

In [40]:
bces=bce=nn.BCEWithLogitsLoss(reduction='mean')
bces((prediction),label)

tensor(0.8186)

In [42]:
import numpy as np
x=prediction.numpy()
y=label.numpy()


array([[0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [47]:
x

array([[ 0.79054606, -0.24446227,  0.21886481, -0.6416272 ,  3.0125504 ],
       [-2.1066737 , -0.57884496, -2.5009742 ,  0.96027946,  0.16292107],
       [ 1.2672343 , -0.70730406,  0.4162808 ,  0.33233863,  0.5622963 ],
       [-0.44948187,  1.3970276 , -0.07386688,  1.2121403 , -1.044815  ]],
      dtype=float32)

In [58]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# binary cross entropy
loss_values = []

epsilon = 1e-8  # to prevent log(0)

for i in range(len(y)):
    batch_loss = []
    for j in range(len(y[0])):
        if y[i][j] == 1:
            loss = -np.log(x[i][j] + epsilon)
        else:
            loss = -np.log(1 - x[i][j] + epsilon)

        batch_loss.append(loss)
    loss_values.append(batch_loss)

print("Loss values:\n", np.mean(loss_values))
print("Loss values:\n", np.array(loss_values))

Loss values:
 9.21039036947585
Loss values:
 [[1.84206807e+01 1.84206807e+01]
 [9.99949993e-05 9.99949993e-05]]
