In [2]:
import numpy as np

In [9]:
r=torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.9045, 0.9732, 0.7766, 0.2994],
        [0.0439, 0.0113, 0.4614, 0.8749],
        [0.6678, 0.7298, 0.2205, 0.5956],
        [0.9717, 0.0805, 0.2715, 0.4087]])
torch.float32


In [5]:
#converting a torch tensor into a numpy array
a = torch.ones(5)
print(a)
b=a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [6]:
#converting numpy array to torch tensor

a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [13]:
#move tensors to gpu
torch.cuda.is_available()


False

In [ ]:
r=r.cuda()
print(r)

In [18]:
#convert list to tensor

a=[2,3,4,5]
print(a)
to_list=torch.tensor(a)
print(to_list,to_list.dtype)

[2, 3, 4, 5]
tensor([2, 3, 4, 5]) torch.int64


In [19]:
#Tensor concatenation


# Step 2: Create two example 2D tensors (like small matrices)
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])

tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

# Show the original tensors
print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# Step 3: Concatenate along dimension 0 (row-wise)
# This stacks them vertically: rows of B are added after rows of A
concat_dim0 = torch.cat((tensor_a, tensor_b), dim=0)
print("\nConcatenated along dim=0 (rows):\n", concat_dim0)

# Step 4: Concatenate along dimension 1 (column-wise)
# This stacks them horizontally: columns of B are added after columns of A
concat_dim1 = torch.cat((tensor_a, tensor_b), dim=1)
print("\nConcatenated along dim=1 (columns):\n", concat_dim1)


Tensor A:
 tensor([[1, 2],
        [3, 4]])
Tensor B:
 tensor([[5, 6],
        [7, 8]])

Concatenated along dim=0 (rows):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenated along dim=1 (columns):
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [20]:
import torch

x = torch.tensor([1, 2, 3])        # shape: [3]

x1 = x.unsqueeze(0)                # shape: [1, 3]
x2 = x.unsqueeze(1)                # shape: [3, 1]
x3 = x.unsqueeze(-1)               # same as x2, shape: [3, 1]
x4 = x.unsqueeze(-2)               # same as x1, shape: [1, 3]

x5 = x.view(1, 3)                  # reshape to 2D: [1, 3]
x6 = x.view(3, 1)                  # reshape to 2D: [3, 1]

x7 = x[None, :]                    # equivalent to unsqueeze(0), shape: [1, 3]
x8 = x[:, None]                    # equivalent to unsqueeze(1), shape: [3, 1]

print(x.shape, x1.shape, x2.shape, x3.shape, x4.shape)
print(x5.shape, x6.shape, x7.shape, x8.shape)


torch.Size([3]) torch.Size([1, 3]) torch.Size([3, 1]) torch.Size([3, 1]) torch.Size([1, 3])
torch.Size([1, 3]) torch.Size([3, 1]) torch.Size([1, 3]) torch.Size([3, 1])


In [ ]:
#AutoGrad

In [23]:
x=torch.tensor([1.,2.,3.], requires_grad=True)
y=torch.tensor([4.,5.,6.], requires_grad=True)

z=x+y
print(z)
print(z.grad_fn)
s=z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [25]:
#now if we backpropagate on s,we can fing the gradients of s with respect to x

s.backward()
print(x.grad)

tensor([2., 2., 2.])


In [26]:
import torch

# Create tensors without gradient tracking
x = torch.randn(2, 2)
y = torch.randn(2, 2)

# Check requires_grad (should be False)
print(x.requires_grad, y.requires_grad)

# Add tensors (no grad_fn since requires_grad=False)
z = x + y
print(z.grad_fn)  # Output: None

# Enable gradient tracking
x.requires_grad_()
y.requires_grad_()

# Add tensors again (now grad_fn is tracked)
z = x + y
print(z.grad_fn)  # Output: <AddBackward0>

# Detach from computation graph
new_z = z.detach()
print(new_z.grad_fn)  # Output: None

# Check requires_grad after operations
print(x.requires_grad)                  # True
print((x + 10).requires_grad)           # True

# Disable grad tracking temporarily
with torch.no_grad():
    print((x + 10).requires_grad)       # False


False False
None
None
True
True
False


In [27]:
import torch

# Step 1: Create a tensor with gradient tracking enabled
x = torch.ones(2, 2, requires_grad=True)
print("x:\n", x)

# Step 2: Perform a computation (creates a new tensor y)
y = x + 2
print("\ny:\n", y)

# Step 3: Check the grad_fn (how y was created)
print("\ny.grad_fn:", y.grad_fn)  # Should be AddBackward0

# Step 4: More operations on y
z = y * y * 3   # same as z = 3 * (x + 2)^2
out = z.mean()  # Take mean of all elements
print("\nz:\n", z)
print("\nout (mean of z):", out)

# Step 5: Backpropagation (computes gradients)
out.backward()

# Step 6: Print gradients w.r.t. x
print("\nGradient of out w.r.t. x:\n", x.grad)


x:
 tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

y:
 tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

y.grad_fn: <AddBackward0 object at 0x0000028F24FF22C0>

z:
 tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

out (mean of z): tensor(27., grad_fn=<MeanBackward0>)

Gradient of out w.r.t. x:
 tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
