In [2]:
import torch

In [3]:
import torchvision

In [5]:
# 1d array
a=torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [6]:
#2d array
b=torch.tensor([[2,2],[2,4],[5,6]])
print(b)

tensor([[2, 2],
        [2, 4],
        [5, 6]])


In [7]:
#size of tensors
print(a.shape)
print(b.shape)

torch.Size([3])
torch.Size([3, 2])


In [10]:
print(b.shape[0])

3


In [15]:
# random numbers
r=torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.8334, 0.3827, 0.8823, 0.3007],
        [0.0934, 0.4663, 0.2464, 0.4193],
        [0.2747, 0.4222, 0.8191, 0.8007],
        [0.7566, 0.0674, 0.3077, 0.3618]])
torch.float32


In [16]:
# random numbers from normal distribution with mean 0 and sd 1
r=torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.2361, 0.6173, 0.7744, 0.8351],
        [0.9825, 0.3015, 0.6994, 0.4139],
        [0.3674, 0.9515, 0.0674, 0.7457],
        [0.1737, 0.2953, 0.7493, 0.5078]])
torch.float32


In [17]:
# create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([9, 8, 6, 7, 9])
torch.int64


In [19]:
# create 2d matrix of size 3x3 with random numbers as above case
in_array2=torch.randint(6,10,(3,3))
print(in_array2)

tensor([[9, 7, 7],
        [7, 7, 6],
        [6, 8, 8]])


In [21]:
#no of elements
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [26]:
# construct 3x3 matrix with zeroes of dtype long
z=torch.zeros(3,3,dtype=torch.long)
print(z)
#with 1s
o=torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [28]:
# convert the datatype of tensor
r2_like=torch.randn_like(r,dtype=torch.double)
print(r2_like)

tensor([[-1.6486, -0.4944, -0.3729, -0.6021],
        [ 0.0345,  0.0143,  0.7519, -0.7604],
        [-0.6739,  0.5323, -0.9711, -0.9231],
        [ 0.4592, -1.1050, -0.3939, -0.8887]], dtype=torch.float64)


In [29]:
#add two tensors
add_result=torch.add(r,r)
print(add_result)

tensor([[0.4723, 1.2345, 1.5487, 1.6702],
        [1.9651, 0.6029, 1.3987, 0.8278],
        [0.7347, 1.9029, 0.1348, 1.4914],
        [0.3474, 0.5907, 1.4986, 1.0157]])


In [31]:
#in place addition (change value of r)
r.add_(r)
print(r)

tensor([[0.4723, 1.2345, 1.5487, 1.6702],
        [1.9651, 0.6029, 1.3987, 0.8278],
        [0.7347, 1.9029, 0.1348, 1.4914],
        [0.3474, 0.5907, 1.4986, 1.0157]])


In [33]:
#operations

print(r[:, 1])
print(r[:, 2])
print(r[:, 3])
num_ten = r[2, 3]
print(num_ten)
print(num_ten.item())
print(r[2, :])


tensor([1.2345, 0.6029, 1.9029, 0.5907])
tensor([1.5487, 1.3987, 0.1348, 1.4986])
tensor([1.6702, 0.8278, 1.4914, 1.0157])
tensor(1.4914)
1.4914175271987915
tensor([0.7347, 1.9029, 0.1348, 1.4914])
