In [1]:
import torch
import torch.nn as nn

In [2]:
layer=nn.Linear(5,5)

In [5]:
layer.weight

Parameter containing:
tensor([[ 0.1714,  0.0589, -0.3561, -0.2975,  0.1181],
        [ 0.2307,  0.3039, -0.2786,  0.3689, -0.3414],
        [ 0.2398,  0.0845,  0.4144,  0.2633,  0.3643],
        [ 0.0368,  0.0864,  0.3070,  0.2591, -0.2033],
        [-0.3340,  0.3619,  0.3606,  0.4442, -0.0570]], requires_grad=True)

In [11]:
#uniform distribution

#nn.init.uniform_(tensor,a=0,b=1)
nn.init.uniform_(layer.weight.data,a=0,b=3)

tensor([[0.3313, 2.7883, 2.0136, 0.3620, 1.7446],
        [0.8797, 2.9807, 1.5487, 2.5566, 1.5918],
        [2.4298, 2.5442, 2.9142, 0.9484, 0.1682],
        [1.2196, 0.7401, 0.1766, 0.7188, 1.9470],
        [0.9467, 0.7874, 1.5623, 2.0583, 2.0315]])

In [12]:
#normal distribution

#nn.init.normal_(tensor,mean=0,std=1)
nn.init.normal_(layer.weight.data,mean=0,std=1)

tensor([[-8.2915e-01,  1.1143e+00, -5.2904e-01, -1.5101e-03, -2.9665e-01],
        [-2.1302e+00,  7.8699e-01, -1.5262e-02, -1.0514e+00, -1.5536e+00],
        [-1.9960e-01,  4.1313e-01,  1.3279e+00,  8.2320e-01,  4.8911e-01],
        [ 9.5063e-02, -1.9595e-01,  6.1978e-01,  3.9485e-02,  4.6043e-01],
        [ 7.7938e-01, -4.7123e-01, -2.3624e-01, -3.6826e-01, -3.6657e-01]])

In [13]:
#smaller values

nn.init.normal_(layer.weight.data,mean=0,std=0.2)

tensor([[-0.0173, -0.1704, -0.1739,  0.1156,  0.0616],
        [-0.5449, -0.1633, -0.0699,  0.1806, -0.0697],
        [-0.1169,  0.0128, -0.1846, -0.0328,  0.1332],
        [ 0.0355, -0.0131,  0.1222,  0.0484,  0.0418],
        [ 0.3480,  0.2294,  0.2489,  0.0336, -0.1324]])

In [14]:
nn.init.constant_(layer.bias, 0)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [16]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [17]:
nn.init.constant_(layer.bias, 8)

Parameter containing:
tensor([8., 8., 8., 8., 8.], requires_grad=True)

In [18]:
layer.bias

Parameter containing:
tensor([8., 8., 8., 8., 8.], requires_grad=True)

In [19]:
#xavier distribution
#torch.nn.init.xavier_uniform_(tensor, gain=1.0, generator=None)

torch.nn.init.xavier_uniform_(layer.weight.data, gain=1.0, generator=None)

tensor([[ 0.3431,  0.5964,  0.5723,  0.3257, -0.3811],
        [-0.2911,  0.2160, -0.5042,  0.0981,  0.5330],
        [ 0.3972, -0.4421,  0.1467, -0.4289,  0.5316],
        [ 0.5922, -0.5453,  0.6238,  0.3823,  0.5657],
        [-0.5373, -0.7597, -0.6434, -0.7015, -0.0741]])

In [20]:
torch.nn.init.xavier_normal_(layer.weight.data, gain=1.0, generator=None)

tensor([[-0.1658,  0.2686,  0.2852,  0.5705, -0.1487],
        [ 0.0728,  0.5245,  0.0788,  0.1713, -0.5748],
        [-0.2460,  0.3287, -0.1638,  0.3132, -0.1517],
        [ 0.2197,  0.1983,  0.0421,  0.5152, -1.1396],
        [ 0.1789,  0.1519,  0.4236, -0.1944, -0.5319]])